[tool.poetry]
name = "dio blog"
version = "0.1.0"
description = ""
authors = ["Vanessa Nery, <nery_van@hotmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
flask = "*"
flask-sqlalchemy = "*"
flask-migrate = "*"
flask-jwt-extended = "^4.7.4"

# pyproject.toml
gunicorn = "*"
psycopg2-binary = "*"
flask-bcrypt = "*"
flask-marshmallow = "*"
marshmallow = "<4"

[tool.pytest]
addopts = ["-ra", "-vvv"]
testpaths = [
    "tests"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-mock = "*"
